# Generated by Django 4.1.5 on 2023-01-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comp", "0002_cityarea_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cityareaenterprise",
            old_name="city_area_id",
            new_name="city_area",
        ),
        migrations.RenameField(
            model_name="cityareaenterprise",
            old_name="enterprise_id",
            new_name="enterprise",
        ),
        migrations.RenameField(
            model_name="enterprise",
            old_name="enterprise_network_id",
            new_name="enterprise_network",
        ),
        migrations.RenameField(
            model_name="enterpriseservice",
            old_name="enterprise_id",
            new_name="enterprise",
        ),
        migrations.RenameField(
            model_name="enterpriseservice",
            old_name="service_id",
            new_name="service",
        ),
    ]
