# Generated by Django 4.1.5 on 2023-01-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comp", "0003_rename_city_area_id_cityareaenterprise_city_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cityarea",
            name="user",
        ),
    ]
