# Generated by Django 4.1.5 on 2023-01-07 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comp", "0005_remove_enterpriseservice_enterprise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="service_category",
            new_name="category",
        ),
    ]
