# Generated by Django 4.1.5 on 2023-01-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comp", "0006_rename_service_category_service_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterpriseservice",
            name="enterprise",
        ),
        migrations.RemoveField(
            model_name="enterpriseservice",
            name="service",
        ),
        migrations.AddField(
            model_name="enterpriseservice",
            name="enterprise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="comp.enterprise",
                verbose_name="Предприятие",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterpriseservice",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="comp.service",
                verbose_name="Услуга/товар",
            ),
            preserve_default=False,
        ),
    ]
